import { render, screen, fireEvent, waitFor } from '@testing-library/react'
import { describe, it, expect, vi, beforeEach } from 'vitest'
import axios from 'axios'
import ReviewPage from '../ReviewPage'

// ------------------------------------------------------------------
// MOCK LLM/BACKEND DATA: This is the mock interactions for the frontend!
// Instead of actually POST-ing to the backend, we intercept the axios
// call and immediately return this object.
// ------------------------------------------------------------------
vi.mock('axios')

const MOCK_BACKEND_RESPONSE = {
  data: {
    score: 85,
    summary: "Mocked frontend test summary.",
    issues: [
      {
        id: 1,
        category: "bug",
        severity: "warning",
        line_number: 10,
        title: "Test Bug",
        description: "This bug is generated by Vitest mock.",
        fix_suggestion: "Fix it.",
        code_before: "foo()",
        code_after: "bar()"
      }
    ]
  }
}

describe('ReviewPage Test Suite', () => {
    beforeEach(() => {
        // Reset all mocks before each test runs
        vi.clearAllMocks()
    })

    it('renders the initial state correctly', () => {
        render(<ReviewPage />)
        // Ensure standard UI elements are loaded
        expect(screen.getByText(/Ready to review/i)).toBeInTheDocument()
        expect(screen.getByText(/Run Review/i)).toBeInTheDocument()
        expect(screen.getByText(/Load sample/i)).toBeInTheDocument()
    })

    it('loads sample code and enables the Run Review button', async () => {
        render(<ReviewPage />)
        
        const loadSampleBtn = screen.getByText(/Load sample/i)
        fireEvent.click(loadSampleBtn)
        
        // Wait for state to update
        await waitFor(() => {
            // The run review button shouldn't be disabled!
            const runReviewBtn = screen.getByRole('button', { name: /Run Review/i })
            expect(runReviewBtn).not.toBeDisabled()
        })
    })

    it('successfully calls API and displays mocked review result', async () => {
        render(<ReviewPage />)

        // Setup the mock response
        axios.post.mockResolvedValueOnce(MOCK_BACKEND_RESPONSE)

        // 1. Load sample code
        const loadSampleBtn = screen.getByText(/Load sample/i)
        fireEvent.click(loadSampleBtn)

        // 2. Click Run Review
        const runReviewBtn = screen.getByRole('button', { name: /Run Review/i })
        fireEvent.click(runReviewBtn)

        // 3. Verify loading state appears
        expect(screen.getByText(/Analysing…/i)).toBeInTheDocument()

        // 4. Verify that axios was called correctly
        await waitFor(() => {
            expect(axios.post).toHaveBeenCalledWith('/api/review', expect.objectContaining({
                filename: 'main.py'
            }))
        })

        // 5. Verify the mocked result (score 85) appears on screen!
        await waitFor(() => {
            expect(screen.getByText('85')).toBeInTheDocument() // The Quality Score
            expect(screen.getByText(/Test Bug/i)).toBeInTheDocument() // The Title of issue
        })
    })

    it('shows error banner on API failure', async () => {
        render(<ReviewPage />)

        // Mock a 500 server error
        axios.post.mockRejectedValueOnce({
            response: { data: { detail: 'Mocked Server Error!' } }
        })

        const loadSampleBtn = screen.getByText(/Load sample/i)
        fireEvent.click(loadSampleBtn)

        const runReviewBtn = screen.getByRole('button', { name: /Run Review/i })
        fireEvent.click(runReviewBtn)

        await waitFor(() => {
            expect(screen.getByText(/Mocked Server Error!/i)).toBeInTheDocument()
        })
    })
})
